const mppCont = [
  {
    Honorific: null,
    Name: 'Anand, Deepak',
    OfficeType: 'Constituency',
    Suite: 'Suite 203',
    Street: '7045 Edwards Boulevard',
    City: 'Mississauga',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'L5S 1X2',
    EmailAddress: 'deepak.anandco@pc.ola.org',
    Telephone: 'Tel:  905-696-0367',
    Fax: 'Fax:  905-696-7545',
  },
  {
    Honorific: null,
    Name: 'Armstrong, Teresa',
    OfficeType: 'Constituency',
    Suite: null,
    Street: '155 Clarke Road',
    City: 'London',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'N5W 5C9',
    EmailAddress: 'tarmstrong-co@ndp.on.ca',
    Telephone: 'Tel:  519-668-1104',
    Fax: 'Fax:  519-668-1941',
  },
  {
    Honorific: 'Hon.',
    Name: 'Arnott, Ted',
    OfficeType: 'Constituency',
    Suite: null,
    Street: '181 St. Andrew Street East  2nd Floor',
    City: 'Fergus',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'N1M 1P9',
    EmailAddress: 'ted.arnottco@pc.ola.org',
    Telephone: 'Toll Free:  1-800-265-2366',
    Fax: 'Fax:  519-787-5249',
  },
  {
    Honorific: null,
    Name: 'Arthur, Ian',
    OfficeType: 'Constituency',
    Suite: 'Suite 2',
    Street: '303 Bagot Street The LaSalle Mews',
    City: 'Kingston',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'K7K 5W7',
    EmailAddress: 'IArthur-CO@ndp.on.ca',
    Telephone: 'Tel:  613-547-2385',
    Fax: 'Fax:  613-547-5001',
  },
  {
    Honorific: null,
    Name: 'Baber, Roman',
    OfficeType: 'Constituency',
    Suite: null,
    Street: '539 Wilson Heights Boulevard',
    City: 'Downsview',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M3H 2V7',
    EmailAddress: 'roman.baberco@pc.ola.org',
    Telephone: 'Tel:  416-630-0080',
    Fax: 'Fax:  416-630-8828',
  },
  {
    Honorific: null,
    Name: 'Babikian, Aris',
    OfficeType: 'Constituency',
    Suite: 'Unit 3',
    Street: '2245 Kennedy Road',
    City: 'Scarborough',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M1T 3G8',
    EmailAddress: 'aris.babikianco@pc.ola.org',
    Telephone: 'Tel:  416-297-6568',
    Fax: 'Fax:  416-297-4962',
  },
  {
    Honorific: null,
    Name: 'Bailey, Robert',
    OfficeType: 'Constituency',
    Suite: 'Suite 102',
    Street: '805 Christina Street North',
    City: 'Point Edward',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'N7V 1X6',
    EmailAddress: 'bob.baileyco@pc.ola.org',
    Telephone: 'Tel:  519-337-0051',
    Fax: 'Fax:  519-337-3246',
  },
  {
    Honorific: null,
    Name: 'Barrett, Toby',
    OfficeType: 'Constituency',
    Suite: null,
    Street: '39 Norfolk Street North',
    City: 'Simcoe',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'N3Y 3N6',
    EmailAddress: '00',
    Telephone: 'Tel:  519-428-0446',
    Fax: 'Fax:  519-428-0835',
  },
  {
    Honorific: null,
    Name: 'Bell, Jessica',
    OfficeType: 'Constituency',
    Suite: 'Unit 103',
    Street: '719 Bloor Street West',
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M5G 1K5',
    EmailAddress: 'JBell-QP@ndp.on.ca',
    Telephone: 'Tel:  416-535-7206',
    Fax: null,
  },
  {
    Honorific: null,
    Name: 'Berns-McGown, Rima',
    OfficeType: 'Constituency',
    Suite: null,
    Street: '1821 Danforth Avenue',
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M4C 1J2',
    EmailAddress: 'RBerns-McGown-CO@ndp.on.ca',
    Telephone: 'Tel:  416-690-1032',
    Fax: 'Fax:  416-690-8420',
  },
  {
    Honorific: 'Hon.',
    Name: 'Bethlenfalvy, Peter',
    OfficeType: 'Constituency',
    Suite: 'Unit 7',
    Street: '300 Kingston Road',
    City: 'Pickering',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'L1V 6Z9',
    EmailAddress: 'peter.bethlenfalvyco@pc.ola.org',
    Telephone: 'Tel:  905-509-0336',
    Fax: 'Fax:  905-509-0334',
  },
  {
    Honorific: null,
    Name: 'Bisson, Gilles',
    OfficeType: 'Constituency',
    Suite: 'Suite 202',
    Street: '60 Wilson Avenue',
    City: 'Timmins',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'P4N 2S7',
    EmailAddress: 'gbisson@ndp.on.ca',
    Telephone: 'Toll Free:  1-800-461-9878  Tel:  705-268-6400',
    Fax: 'Fax:  705-266-9125',
  },
  {
    Honorific: null,
    Name: 'Bouma, Will',
    OfficeType: 'Constituency',
    Suite: 'Suite 101',
    Street: '96 Nelson Street',
    City: 'Brantford',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'N3T 2N1',
    EmailAddress: 'will.bouma@pc.ola.org',
    Telephone: 'Tel:  519-759-0361',
    Fax: 'Fax:  519-759-6439',
  },
  {
    Honorific: null,
    Name: 'Bourgouin, Guy',
    OfficeType: 'Constituency',
    Suite: null,
    Street: '28 Circle Street',
    City: 'Kapuskasing',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'P5N 1T7',
    EmailAddress: 'GBourgouin-QP@ndp.on.ca',
    Telephone: 'Tel:  705-335-6400',
    Fax: 'Fax:  705-337-6869',
  },
  {
    Honorific: null,
    Name: 'Burch, Jeff',
    OfficeType: 'Constituency',
    Suite: 'Unit 102',
    Street: '60 King Street',
    City: 'Welland',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'L3B 6A4',
    EmailAddress: 'JBurch-CO@ndp.on.ca',
    Telephone: 'Tel:  905-732-6884',
    Fax: 'Fax:  905-732-9782',
  },
  {
    Honorific: null,
    Name: 'Calandra, Paul',
    OfficeType: 'Constituency',
    Suite: 'Suite 400',
    Street: '37 Sandiford Drive',
    City: 'Stouffville',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'L4A 3Z2',
    EmailAddress: '00',
    Telephone: 'Toll Free:  866-531-9551  Tel:  905-642-2588',
    Fax: 'Fax:  905-642-1618',
  },
  {
    Honorific: 'Hon.',
    Name: 'Cho, Raymond Sung Joon',
    OfficeType: 'Constituency',
    Suite: 'Unit B',
    Street: '4559 Sheppard Avenue East',
    City: 'Scarborough',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M1S 1V3',
    EmailAddress: 'raymond.choco@pc.ola.org',
    Telephone: 'Tel:  416-297-5040',
    Fax: 'Fax:  416-297-6767',
  },
  {
    Honorific: null,
    Name: 'Cho, Stan',
    OfficeType: 'Constituency',
    Suite: null,
    Street: '111 Sheppard Avenue West',
    City: 'North York',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M2N 1M7',
    EmailAddress: '00',
    Telephone: 'Tel:  416-733-7878',
    Fax: 'Fax:  416-733-7709',
  },
  {
    Honorific: 'Hon.',
    Name: 'Clark, Steve',
    OfficeType: 'Constituency',
    Suite: 'Suite 101',
    Street: '100 Strowger Boulevard',
    City: 'Brockville',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'K6V 5J9',
    EmailAddress: '00',
    Telephone: 'Toll Free:  1-800-267-4408  Tel:  613-342-9522',
    Fax: 'Fax:  613-342-2501',
  },
  {
    Honorific: null,
    Name: 'Coe, Lorne',
    OfficeType: 'Constituency',
    Suite: 'Suite 101',
    Street: '114 Dundas Street East',
    City: 'Whitby',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'L1N 2H7',
    EmailAddress: 'lorne.coeco@pc.ola.org',
    Telephone: 'Tel:  905-430-1141',
    Fax: 'Fax:  905-430-1840',
  },
  {
    Honorific: null,
    Name: 'Coteau, Michael',
    OfficeType: 'Constituency',
    Suite: 'Suite L02',
    Street: '1200 Lawrence Avenue East',
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M3A 1C1',
    EmailAddress: 'mcoteau.mpp.co@liberal.ola.org',
    Telephone: 'Tel:  416-494-6856',
    Fax: 'Fax:  416-494-9937',
  },
  {
    Honorific: null,
    Name: 'Crawford, Stephen',
    OfficeType: 'Constituency',
    Suite: 'Unit 2',
    Street: '2318 Lakeshore Road West',
    City: 'Oakville',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'L6L 1H3',
    EmailAddress: 'stephen.crawfordco@pc.ola.org',
    Telephone: 'Tel:  905-827-5141',
    Fax: 'Fax:  905-827-3786',
  },
  {
    Honorific: null,
    Name: 'Cuzzetto, Rudy',
    OfficeType: 'Constituency',
    Suite: 'Unit 1 &amp; 2',
    Street: '120 Lakeshore Road West',
    City: 'Mississauga',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'L5H 1E8',
    EmailAddress: 'rudy.cuzzettoco@pc.ola.org',
    Telephone: 'Tel:  905-274-8228',
    Fax: 'Fax:  905-274-8552',
  },
  {
    Honorific: null,
    Name: 'Des Rosiers, Nathalie',
    OfficeType: 'Constituency',
    Suite: null,
    Street: '237 Montreal Road',
    City: 'Vanier',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'K1L 6C7',
    EmailAddress: 'NDesRosiers.mpp.CO@liberal.ola.org',
    Telephone: 'Tel:  613-744-4484',
    Fax: 'Fax:  613-744-0889',
  },
  {
    Honorific: null,
    Name: 'Downey, Doug',
    OfficeType: 'Constituency',
    Suite: 'Unit 14',
    Street: '20 Bell Farm Road',
    City: 'Barrie',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'L4M 6E4',
    EmailAddress: 'doug.downeyco@pc.ola.org',
    Telephone: 'Tel:  705-726-5538',
    Fax: 'Fax:  705-726-2880',
  },
  {
    Honorific: null,
    Name: 'Dunlop,  Jill',
    OfficeType: 'Constituency',
    Suite: 'Unit 108',
    Street: '210 Memorial Avenue',
    City: 'Orillia',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'L3V 7V1',
    EmailAddress: 'jill.dunlopco@pc.ola.org',
    Telephone: 'Tel:  705-326-3246',
    Fax: 'Fax:  705-326-9579',
  },
  {
    Honorific: null,
    Name: 'Dunlop,  Jill',
    OfficeType: 'Constituency',
    Suite: 'Unit 6',
    Street: '295 King Street  TD Canada Trust Bank Plaza',
    City: 'Midland',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'L4R 3M5',
    EmailAddress: '00',
    Telephone: 'Tel:  705-526-8671',
    Fax: 'Fax:  705-526-8600',
  },
  {
    Honorific: 'Hon.',
    Name: 'Elliott,  Christine',
    OfficeType: 'Constituency',
    Suite: 'Suite 203',
    Street: '238 Wellington Street East',
    City: 'Aurora',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'L4G 1J5',
    EmailAddress: 'christine.elliottco@pc.ola.org',
    Telephone: 'Tel:  905-750-0019',
    Fax: 'Fax:  905-750-0050',
  },
  {
    Honorific: 'Hon.',
    Name: 'Fedeli, Victor',
    OfficeType: 'Constituency',
    Suite: null,
    Street: '165 Main Street East',
    City: 'North Bay',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'P1B 1A9',
    EmailAddress: 'vic.fedelico@pc.ola.org',
    Telephone: 'Tel:  705-474-8340',
    Fax: 'Fax:  705-474-9747',
  },
  {
    Honorific: null,
    Name: 'Fife,  Catherine',
    OfficeType: 'Constituency',
    Suite: 'Suite 220',
    Street: '100 Regina Street South',
    City: 'Waterloo',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'N2J 4P9',
    EmailAddress: 'cfife-co@ndp.on.ca',
    Telephone: 'Tel:  519-725-3477',
    Fax: 'Fax:  519-725-3667',
  },
  {
    Honorific: 'Hon.',
    Name: 'Ford,  Doug',
    OfficeType: 'Constituency',
    Suite: null,
    Street: '823 Albion Road',
    City: 'Etobicoke',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M9V 1A3',
    EmailAddress: 'doug.fordco@pc.ola.org',
    Telephone: 'Tel:  416-745-2859',
    Fax: 'Fax:  416-745-4601',
  },
  {
    Honorific: null,
    Name: 'Fraser,  John',
    OfficeType: 'Constituency',
    Suite: null,
    Street: '1828 Bank Street',
    City: 'Ottawa',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'K1V 7Y6',
    EmailAddress: 'Jfraser.mpp.co@liberal.ola.org',
    Telephone: 'Tel:  613-736-9573',
    Fax: 'Fax:  613-736-7374',
  },
  {
    Honorific: null,
    Name: 'French, Jennifer',
    OfficeType: 'Constituency',
    Suite: 'Unit 2',
    Street: '78 Centre Street North',
    City: 'Oshawa',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'L1G 4B6',
    EmailAddress: 'JFrench-CO@ndp.on.ca',
    Telephone: 'Tel:  905-723-2411',
    Fax: 'Fax:  905-723-1054',
  },
  {
    Honorific: 'Hon.',
    Name: 'Fullerton,  Merrilee',
    OfficeType: 'Constituency',
    Suite: 'Suite 100',
    Street: '240 Michael Cowpland Drive',
    City: 'Kanata',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'K2M 1P6',
    EmailAddress: '00',
    Telephone: 'Tel:  613-599-3000',
    Fax: 'Fax:  613-599-8183',
  },
  {
    Honorific: null,
    Name: 'Gates,  Wayne',
    OfficeType: 'Constituency',
    Suite: null,
    Street: '265 High Street  Douglas Heights Seniors Centre',
    City: 'Fort Erie',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'L2A 3R4',
    EmailAddress: 'wgates-co@ndp.on.ca',
    Telephone: 'Tel:  905-871-8868',
    Fax: 'Fax:  905-871-4717',
  },
  {
    Honorific: null,
    Name: 'Gates,  Wayne',
    OfficeType: 'Constituency',
    Suite: 'Unit 1',
    Street: '6746 Morrison Street',
    City: 'Niagara Falls',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'L2E 6Z8',
    EmailAddress: 'wgates-co@ndp.on.ca',
    Telephone: 'Tel:  905-357-0681',
    Fax: 'Fax:  905-357-9456',
  },
  {
    Honorific: null,
    Name: 'Gélinas, France',
    OfficeType: 'Constituency',
    Suite: 'Suite 15',
    Street: '5085 Highway 69 North',
    City: 'Hanmer',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'P3P 1P7',
    EmailAddress: 'fgelinas-co@ndp.on.ca',
    Telephone: 'Tel:  705-969-3621',
    Fax: 'Fax:  705-969-3538',
  },
  {
    Honorific: null,
    Name: 'Gill,  Parm',
    OfficeType: 'Constituency',
    Suite: 'Unit 115',
    Street: '450 Bronte Street South',
    City: 'Milton',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'L9T 5B7',
    EmailAddress: 'parm.gillco@pc.ola.org',
    Telephone: 'Tel:  905-878-1729',
    Fax: 'Fax:  905-878-5144',
  },
  {
    Honorific: null,
    Name: 'Glover,  Chris',
    OfficeType: 'Constituency',
    Suite: 'Unit A',
    Street: '226 Bathurst Street',
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M5T 2R9',
    EmailAddress: 'CGlover-CO@ndp.on.ca',
    Telephone: 'Tel:  416-603-9664',
    Fax: 'Fax:  416-603-1214',
  },
  {
    Honorific: null,
    Name: 'Gravelle,  Michael',
    OfficeType: 'Constituency',
    Suite: null,
    Street: '179 Algoma Street South',
    City: 'Thunder Bay',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'P7B 3C1',
    EmailAddress: 'mgravelle.mpp.co@liberal.ola.org',
    Telephone: 'Tel:  807-345-3647',
    Fax: 'Fax:  807-345-2922',
  },
  {
    Honorific: null,
    Name: 'Gretzky, Lisa',
    OfficeType: 'Constituency',
    Suite: 'Unit 5',
    Street: '321 Tecumseh Road East',
    City: 'Windsor',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'N8X 2R5',
    EmailAddress: 'LGretzky-CO@ndp.on.ca',
    Telephone: 'Tel:  519-977-7191',
    Fax: 'Fax:  519-977-7029',
  },
  {
    Honorific: 'Hon.',
    Name: 'Hardeman,  Ernie',
    OfficeType: 'Constituency',
    Suite: null,
    Street: '12 Perry Street  2nd Floor',
    City: 'Woodstock',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'N4S 3C2',
    EmailAddress: 'ernie.hardemanco@pc.ola.org',
    Telephone: 'Toll Free:  1-800-265-4046  Tel:  519-537-5222',
    Fax: 'Fax:  519-537-3577',
  },
  {
    Honorific: null,
    Name: 'Harden,  Joel',
    OfficeType: 'Constituency',
    Suite: null,
    Street: '109 Catherine Street',
    City: 'Ottawa',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'K2P 0P4',
    EmailAddress: 'JHarden-CO@ndp.on.ca',
    Telephone: 'Tel:  613-722-6414',
    Fax: 'Fax:  613-722-6703',
  },
  {
    Honorific: null,
    Name: 'Harris,  Mike',
    OfficeType: 'Constituency',
    Suite: 'Unit 3 &amp; 4',
    Street: '63 Arthur Street South',
    City: 'Elmira',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'N3B 2M6',
    EmailAddress: 'mike.harrisco@pc.ola.org',
    Telephone: 'Tel:  519-669-2090',
    Fax: 'Fax:  519-669-0476',
  },
  {
    Honorific: null,
    Name: 'Hassan,  Faisal',
    OfficeType: 'Constituency',
    Suite: null,
    Street: '1965 Weston Road',
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M9N 1W8',
    EmailAddress: 'FHassan-CO@ndp.on.ca',
    Telephone: 'Tel:  416-243-7984',
    Fax: 'Fax:  416-243-0327',
  },
  {
    Honorific: null,
    Name: 'Hatfield,  Percy',
    OfficeType: 'Constituency',
    Suite: 'Unit 1',
    Street: '5452 Tecumseh Road East',
    City: 'Windsor',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'N8T 1C7',
    EmailAddress: 'PHatfield-co@ndp.on.ca',
    Telephone: 'Tel:  519-251-5199',
    Fax: 'Fax:  519-251-5299',
  },
  {
    Honorific: null,
    Name: 'Hillier,  Randy',
    OfficeType: 'Constituency',
    Suite: 'Unit 1',
    Street: '105 Dufferin Street',
    City: 'Perth',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'K7H 3A5',
    EmailAddress: 'randy.hillierco@pc.ola.org',
    Telephone: 'Tel:  613-267-8239',
    Fax: 'Fax:  613-267-7398',
  },
  {
    Honorific: null,
    Name: 'Hogarth,  Christine',
    OfficeType: 'Constituency',
    Suite: null,
    Street: '933 The Queensway',
    City: 'Etobicoke',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M8Z 1P3',
    EmailAddress: 'christine.hogarthco@pc.ola.org',
    Telephone: 'Tel:  416-259-2249',
    Fax: 'Fax:  416-259-3704',
  },
  {
    Honorific: null,
    Name: 'Horwath,  Andrea',
    OfficeType: 'Constituency',
    Suite: 'Suite 200',
    Street: '20 Hughson Street South',
    City: 'Hamilton',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'L8N 2A1',
    EmailAddress: 'ahorwath-co@ndp.on.ca',
    Telephone: 'Tel:  905-544-9644',
    Fax: 'Fax:  905-544-5152',
  },
  {
    Honorific: null,
    Name: 'Hunter,  Mitzie',
    OfficeType: 'Constituency',
    Suite: 'Unit 109',
    Street: '4117 Lawrence Avenue East',
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M1E 2S2',
    EmailAddress: 'mhunter.mpp.co@liberal.ola.org',
    Telephone: 'Tel:  416-281-2787',
    Fax: 'Fax:  416-281-2360',
  },
  {
    Honorific: 'Hon.',
    Name: 'Jones,  Sylvia',
    OfficeType: 'Constituency',
    Suite: null,
    Street: '244 Broadway Avenue',
    City: 'Orangeville',
    Province: 'ON',
    Country: 'Canada',
    PostalCode: 'L9W 1K5',
    EmailAddress: 'sylvia.jonesco@pc.ola.org',
    Telephone: 'Tel:  519-941-7751',
    Fax: 'Fax:  519-941-3246',
  },
  {
    Honorific: null,
    Name: 'Kanapathi,  Logan',
    OfficeType: 'Constituency',
    Suite: 'Unit 5',
    Street: '450 Alden Road',
    City: 'Markham',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'L3R 5H4',
    EmailAddress: 'logan.kanapathico@pc.ola.org',
    Telephone: 'Tel:  905-305-1935',
    Fax: 'Fax:  905-305-1938',
  },
  {
    Honorific: null,
    Name: 'Karahalios,  Belinda',
    OfficeType: 'Constituency',
    Suite: null,
    Street: '498 Eagle Street North',
    City: 'Cambridge',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'N3H 1C2',
    EmailAddress: 'belinda.karahaliosco@pc.ola.org',
    Telephone: '00',
    Fax: 'Fax:  519-650-3918',
  },
  {
    Honorific: null,
    Name: 'Karpoche,  Bhutila',
    OfficeType: 'Constituency',
    Suite: null,
    Street: '2849 Dundas Street West',
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M6P 1Y6',
    EmailAddress: 'BKarpoche-CO@ndp.on.ca',
    Telephone: 'Tel:  416-763-5630',
    Fax: 'Fax:  416-763-5640',
  },
  {
    Honorific: null,
    Name: 'Ke, Vincent',
    OfficeType: 'Constituency',
    Suite: 'Suite 103',
    Street: '2175 Sheppard Avenue East',
    City: 'North York',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M2J 1W8',
    EmailAddress: 'vincent.keco@pc.ola.org',
    Telephone: 'Tel:  416-494-8778',
    Fax: 'Fax:  416-494-0110',
  },
  {
    Honorific: null,
    Name: 'Kernaghan,  Terence',
    OfficeType: 'Constituency',
    Suite: 'Unit 105',
    Street: '400 York Street',
    City: 'London',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'N6B 3N2',
    EmailAddress: 'TKernaghan-CO@ndp.on.ca',
    Telephone: 'Tel:  519-432-7339',
    Fax: 'Fax:  519-432-0613',
  },
  {
    Honorific: null,
    Name: 'Khanjin,  Andrea',
    OfficeType: 'Constituency',
    Suite: 'Unit 1',
    Street: '237 Mapleview Drive East',
    City: 'Barrie',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'L4N 0W5',
    EmailAddress: 'andrea.khanjinco@pc.ola.org',
    Telephone: 'Tel:  705-722-0575',
    Fax: 'Fax:  705-722-8835',
  },
  {
    Honorific: null,
    Name: 'Kramp,  Daryl',
    OfficeType: 'Constituency',
    Suite: 'Suite 6',
    Street: '6 Dundas Street East  Napanee Downtown Business Hub',
    City: 'Napanee',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'K7R 3L4',
    EmailAddress: '00',
    Telephone: 'Tel:  613-308-9625',
    Fax: 'Fax:  613-308-9685',
  },
  {
    Honorific: null,
    Name: 'Kramp,  Daryl',
    OfficeType: 'Constituency',
    Suite: null,
    Street: '26A St. Lawrence Street West  P.O. BOX 70',
    City: 'Madoc',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'K0K 2K0',
    EmailAddress: '00',
    Telephone: 'Toll Free:  855-229-6676 Tel:  343-600-3310',
    Fax: 'Fax:  343-600-3329',
  },
  {
    Honorific: null,
    Name: 'Lalonde, Marie-France',
    OfficeType: 'Constituency',
    Suite: 'Unit 206',
    Street: '250 Centrum Boulevard',
    City: 'Orleans',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'K1E 3J1',
    EmailAddress: 'mflalonde.mpp.co@liberal.ola.org',
    Telephone: 'Tel:  613-834-8679',
    Fax: 'Fax:  613-834-7647',
  },
  {
    Honorific: null,
    Name: 'Lecce,  Stephen',
    OfficeType: 'Constituency',
    Suite: 'Unit 1',
    Street: '2220 King Road',
    City: 'King City',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'L7B 1L3',
    EmailAddress: '00',
    Telephone: 'Tel:  647-560-9700',
    Fax: 'Fax:  647-560-9701',
  },
  {
    Honorific: null,
    Name: 'Lindo, Laura Mae',
    OfficeType: 'Constituency',
    Suite: 'Unit 3',
    Street: '379 Queen Street South',
    City: 'Kitchener',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'N2G 1W6',
    EmailAddress: 'LLindo-CO@ndp.on.ca',
    Telephone: 'Tel:  519-579-5460',
    Fax: 'Fax:  519-579-2121',
  },
  {
    Honorific: 'Hon.',
    Name: 'MacLeod, Lisa',
    OfficeType: 'Constituency',
    Suite: 'Unit 10',
    Street: '3500 Fallowfield Road',
    City: 'Nepean',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'K2J 4A7',
    EmailAddress: 'lisa.macleodco@pc.ola.org',
    Telephone: 'Tel:  613-823-2116',
    Fax: 'Fax:  613-823-8284',
  },
  {
    Honorific: null,
    Name: 'Mamakwa,  Sol',
    OfficeType: 'Constituency',
    Suite: 'Unit 104',
    Street: '73 King Street  P.O. BOX 176',
    City: 'Sioux Lookout',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'P8T 1A1',
    EmailAddress: 'SMamakwa-CO@ndp.on.ca',
    Telephone: 'Tel:  807-737-2210',
    Fax: 'Fax:  807-737-1592',
  },
  {
    Honorific: null,
    Name: 'Mantha,  Michael',
    OfficeType: 'Constituency',
    Suite: null,
    Street: '18 Mary Walk',
    City: 'Elliot Lake',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'P5A 2A1',
    EmailAddress: 'mmantha-co@ndp.on.ca',
    Telephone: 'Toll Free:  1-800-831-1899 Tel:  705-461-9710',
    Fax: 'Fax:  705-461-9720',
  },
  {
    Honorific: null,
    Name: 'Martin,  Robin',
    OfficeType: 'Constituency',
    Suite: null,
    Street: '2882 Dufferin Street',
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M6B 3S6',
    EmailAddress: 'robin.martinco@pc.ola.org',
    Telephone: 'Tel:  416-781-2395',
    Fax: 'Fax:  416-781-4116',
  },
  {
    Honorific: null,
    Name: 'Martow, Gila',
    OfficeType: 'Constituency',
    Suite: 'Unit 4',
    Street: '1136 Centre Street  Centre Street Square',
    City: 'Thornhill',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'L4J 3M8',
    EmailAddress: 'gila.martowco@pc.ola.org',
    Telephone: 'Tel:  905-731-8462',
    Fax: 'Fax:  905-731-2984',
  },
  {
    Honorific: null,
    Name: 'McDonell,  Jim',
    OfficeType: 'Constituency',
    Suite: null,
    Street: '120 Second Street West  Time Square',
    City: 'Cornwall',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'K6J 1G5',
    EmailAddress: 'jim.mcdonellco@pc.ola.org',
    Telephone: 'Tel:  613-933-6513',
    Fax: 'Fax:  613-933-6449',
  },
  {
    Honorific: null,
    Name: 'McKenna, Jane',
    OfficeType: 'Constituency',
    Suite: 'Unit 104',
    Street: '472 Brock Avenue',
    City: 'Burlington',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'L7S 1N1',
    EmailAddress: '00',
    Telephone: 'Tel:  905-639-7924',
    Fax: 'Fax:  905-639-3284',
  },
  {
    Honorific: 'Hon.',
    Name: 'McNaughton,  Monte',
    OfficeType: 'Constituency',
    Suite: null,
    Street: '360 James Street',
    City: 'Wallaceburg',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'N8A 2N5',
    EmailAddress: 'monte.mcnaughtonco@pc.ola.org',
    Telephone: 'Tel:  519-627-1015',
    Fax: 'Fax:  519-627-7174',
  },
  {
    Honorific: 'Hon.',
    Name: 'McNaughton,  Monte',
    OfficeType: 'Constituency',
    Suite: null,
    Street: '81 Front Street West',
    City: 'Strathroy',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'N7G 1X6',
    EmailAddress: 'monte.mcnaughtonco@pc.ola.org',
    Telephone: 'Tel:  519-245-8696',
    Fax: 'Fax:  519-245-8697',
  },
  {
    Honorific: null,
    Name: 'Miller, Norman',
    OfficeType: 'Constituency',
    Suite: null,
    Street: '289 Queenston Road',
    City: 'Hamilton',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'L8K 1H2',
    EmailAddress: 'pmiller-co@ndp.on.ca',
    Telephone: 'Tel:  905-545-0114',
    Fax: 'Fax:  905-545-9024',
  },
  {
    Honorific: null,
    Name: 'Miller,  Norman',
    OfficeType: 'Constituency',
    Suite: null,
    Street: '17 James Street',
    City: 'Parry Sound',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'P2A 1T4',
    EmailAddress: '00',
    Telephone: 'Toll Free:  1-888-701-1176 Tel:  705-746-4266',
    Fax: 'Fax:  705-746-1578',
  },
  {
    Honorific: null,
    Name: 'Miller,  Norman',
    OfficeType: 'Constituency',
    Suite: 'Unit 1',
    Street: '165 Manitoba Street',
    City: 'Bracebridge',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'P1L 1S3',
    EmailAddress: '00',
    Telephone: 'Toll Free:  1-888-267-4826 Tel:  705-645-8538',
    Fax: 'Fax:  705-645-8148',
  },
  {
    Honorific: null,
    Name: 'Mitas, Christina Maria',
    OfficeType: 'Constituency',
    Suite: null,
    Street: '2063 Lawrence Avenue East',
    City: 'Scarborough',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M1R 2Z4',
    EmailAddress: 'christina.mitasco@pc.ola.org',
    Telephone: 'Tel:  416-615-2183',
    Fax: 'Fax:  416-615-2011',
  },
  {
    Honorific: null,
    Name: 'Monteith-Farrell, Judith',
    OfficeType: 'Constituency',
    Suite: null,
    Street: '409 George Street',
    City: 'Thunder Bay',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'P7E 5Y9',
    EmailAddress: 'JMonteith-Farrell-CO@ndp.on.ca',
    Telephone: 'Toll Free:  833-673-4129 Tel:  807-622-1920',
    Fax: 'Fax:  807-622-3263',
  },
  {
    Honorific: 'Hon.',
    Name: 'Mulroney, Caroline',
    OfficeType: 'Constituency',
    Suite: 'Unit 8',
    Street: '45 Grist Mill Road',
    City: 'Holland Landing',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'L9N 1M7',
    EmailAddress: 'caroline.mulroneyco@pc.ola.org',
    Telephone: 'Tel:  905-895-1555',
    Fax: 'Fax:  905-895-0337',
  },
  {
    Honorific: null,
    Name: 'Natyshak, Taras',
    OfficeType: 'Constituency',
    Suite: null,
    Street: '316 Talbot Street North',
    City: 'Essex',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'N8M 2E1',
    EmailAddress: 'tnatyshak-co@ndp.on.ca',
    Telephone: 'Toll Free:  1-800-265-3909 Tel:  519-776-6420',
    Fax: 'Fax:  519-776-6980',
  },
  {
    Honorific: null,
    Name: 'Nicholls,  Rick',
    OfficeType: 'Constituency',
    Suite: 'Suite 100',
    Street: '111 Heritage Road',
    City: 'Chatham',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'N7M 5W7',
    EmailAddress: 'rick.nichollsco@pc.ola.org',
    Telephone: 'Toll Free:  1-800-265-3992  Tel:  519-351-0510',
    Fax: 'Fax:  519-351-7714',
  },
  {
    Honorific: null,
    Name: 'Nicholls,  Rick',
    OfficeType: 'Constituency',
    Suite: 'Unit B',
    Street: '115 Erie Street North',
    City: 'Leamington',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'N8H 3A3',
    EmailAddress: '00',
    Telephone: 'Tel:  519-326-3367',
    Fax: 'Fax:  519-326-0404',
  },
  {
    Honorific: null,
    Name: 'Oosterhoff, Sam',
    OfficeType: 'Constituency',
    Suite: 'Unit M1',
    Street: '4961 King Street East',
    City: 'Beamsville',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'L0R 1B0',
    EmailAddress: 'sam.oosterhoffco@pc.ola.org',
    Telephone: 'Tel:  905-563-1755',
    Fax: 'Fax:  905-563-1317',
  },
  {
    Honorific: null,
    Name: 'Pang, Billy',
    OfficeType: 'Constituency',
    Suite: 'Unit 602',
    Street: '3601 Highway 7 East',
    City: 'Markham',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'L3R 0M3',
    EmailAddress: '00',
    Telephone: 'Tel:  905-474-3288',
    Fax: 'Fax:  905-474-2878',
  },
  {
    Honorific: null,
    Name: 'Park, Lindsey',
    OfficeType: 'Constituency',
    Suite: null,
    Street: '23 King Street West',
    City: 'Bowmanville',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'L1C 1R2',
    EmailAddress: 'lindsey.parkco@pc.ola.org',
    Telephone: 'Tel:  905-697-1501',
    Fax: 'Fax:  905-697-1506',
  },
  {
    Honorific: null,
    Name: 'Parsa, Michael',
    OfficeType: 'Constituency',
    Suite: 'Suite 403',
    Street: '13291 Yonge Street',
    City: 'Richmond Hill',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'L4E 4L6',
    EmailAddress: 'michael.parsaco@pc.ola.org',
    Telephone: 'Toll Free:  888-486-5352 Tel:  905-773-6250',
    Fax: 'Fax:  905-773-8158',
  },
  {
    Honorific: null,
    Name: 'Pettapiece, Randy',
    OfficeType: 'Constituency',
    Suite: 'Unit 2',
    Street: '55 Lorne Avenue East',
    City: 'Stratford',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'N5A 6S4',
    EmailAddress: 'randy.pettapiececo@pc.ola.org',
    Telephone: 'Tel:  519-272-0660',
    Fax: 'Fax:  519-272-1064',
  },
  {
    Honorific: 'Hon.',
    Name: 'Phillips, Rod',
    OfficeType: 'Constituency',
    Suite: 'Suite 201A',
    Street: '50 Commercial Avenue',
    City: 'Ajax',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'L1S 2H5',
    EmailAddress: 'rod.phillipsco@pc.ola.org',
    Telephone: 'Tel:  905-427-2060',
    Fax: 'Fax:  905-427-6976',
  },
  {
    Honorific: null,
    Name: 'Piccini, David',
    OfficeType: 'Constituency',
    Suite: 'Unit 7',
    Street: '513 Division Street',
    City: 'Cobourg',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'K9A 5G6',
    EmailAddress: 'david.piccinico@pc.ola.org',
    Telephone: 'Tel:  905-372-4000',
    Fax: 'Fax:  905-372-1672',
  },
  {
    Honorific: null,
    Name: 'Rakocevic,  Tom',
    OfficeType: 'Constituency',
    Suite: 'Unit 38',
    Street: '2300 Finch Avenue West',
    City: 'North York',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M9M 2Y3',
    EmailAddress: 'TRakocevic-CO@ndp.on.ca',
    Telephone: 'Tel:  416-743-7272',
    Fax: 'Fax:  416-743-3292',
  },
  {
    Honorific: null,
    Name: 'Rasheed,  Kaleed',
    OfficeType: 'Constituency',
    Suite: 'Unit 315',
    Street: '1420 Burnhamthorpe Road East',
    City: 'Mississauga',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'L4X 2Z9',
    EmailAddress: 'kaleed.rasheedco@pc.ola.org',
    Telephone: 'Tel:  905-238-1751',
    Fax: 'Fax:  905-238-4918',
  },
  {
    Honorific: 'Hon.',
    Name: 'Rickford,  Greg',
    OfficeType: 'Constituency',
    Suite: 'Unit 2',
    Street: '439 Government Street',
    City: 'Dryden',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'P8N 2P4',
    EmailAddress: 'greg.rickford@pc.ola.org',
    Telephone: 'Tel:  807-223-6456',
    Fax: 'Fax:  807-223-6593',
  },
  {
    Honorific: 'Hon.',
    Name: 'Rickford,  Greg',
    OfficeType: 'Constituency',
    Suite: 'Unit 1',
    Street: '279 Scott Street',
    City: 'Fort Frances',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'P9A 1G8',
    EmailAddress: 'greg.rickford@pc.ola.org',
    Telephone: 'Tel:  807-274-7619',
    Fax: 'Fax:  807-274-3721',
  },
  {
    Honorific: 'Hon.',
    Name: 'Rickford,  Greg',
    OfficeType: 'Constituency',
    Suite: null,
    Street: '300 McClellan Avenue East Room',
    City: 'Kenora',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'P9N 1A8',
    EmailAddress: 'greg.rickford@pc.ola.org',
    Telephone: 'Tel:  807-467-2415',
    Fax: 'Fax:  807-467-2641',
  },
  {
    Honorific: null,
    Name: 'Roberts,  Jeremy',
    OfficeType: 'Constituency',
    Suite: 'Suite 201',
    Street: '2249 Carling Avenue',
    City: 'Ottawa',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'K2B 7E9',
    EmailAddress: 'jeremy.robertsco@pc.ola.org',
    Telephone: 'Tel:  613-721-8075',
    Fax: 'Fax:  613-721-5756',
  },
  {
    Honorific: null,
    Name: 'Romano,  Ross',
    OfficeType: 'Constituency',
    Suite: 'Suite 102',
    Street: '390 Bay Street',
    City: 'Sault Ste Marie',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'P6A 1X2',
    EmailAddress: 'ross.romanoco@pc.ola.org',
    Telephone: 'Tel:  705-949-6959',
    Fax: 'Fax:  705-946-6269',
  },
  {
    Honorific: null,
    Name: 'Sandhu,  Amarjot',
    OfficeType: 'Constituency',
    Suite: 'Unit 309',
    Street: '10 Gillingham Drive',
    City: 'Brampton',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'L6X 0G6',
    EmailAddress: 'amarjot.sandhuco@pc.ola.org',
    Telephone: 'Tel:  905-595-1532',
    Fax: 'Fax:  905-457-8496',
  },
  {
    Honorific: null,
    Name: 'Sarkaria,  Prabmeet Singh',
    OfficeType: 'Constituency',
    Suite: 'Unit 412A',
    Street: '7700 Hurontario Street',
    City: 'Brampton',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'L6Y 4M3',
    EmailAddress: '00',
    Telephone: 'Tel:  905-796-8669',
    Fax: 'Fax:  905-796-8069',
  },
  {
    Honorific: null,
    Name: 'Sattler, Peggy',
    OfficeType: 'Constituency',
    Suite: 'Unit 106',
    Street: '240 Commissioners Road West',
    City: 'London',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'N6J 1Y1',
    EmailAddress: 'Psattler-co@ndp.on.ca',
    Telephone: 'Tel:  519-657-3120',
    Fax: 'Fax:  519-657-0368',
  },
  {
    Honorific: null,
    Name: 'Schreiner,  Mike',
    OfficeType: 'Constituency',
    Suite: null,
    Street: '173 Woolwich Street',
    City: 'Guelph',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'N1H 3V4',
    EmailAddress: 'mschreiner-co@ola.org',
    Telephone: 'Tel:  519-836-4190',
    Fax: 'Fax:  519-836-4191',
  },
  {
    Honorific: 'Hon.',
    Name: 'Scott, Laurie',
    OfficeType: 'Constituency',
    Suite: null,
    Street: '14 Lindsay Street North',
    City: 'Lindsay',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'K9V 1T4',
    EmailAddress: 'laurie.scottco@pc.ola.org',
    Telephone: 'Toll Free:  1-800-424-2490',
    Fax: null,
  },
  {
    Honorific: null,
    Name: 'Simard, Amanda',
    OfficeType: 'Constituency',
    Suite: 'Suite 116',
    Street: '151 Main Street East',
    City: 'Hawkesbury',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'K6A 1A1',
    EmailAddress: 'amanda.simard@pc.ola.org',
    Telephone: 'Toll Free:  800-294-8250  Tel:  613-632-2706',
    Fax: 'Fax:  613-632-1554',
  },
  {
    Honorific: null,
    Name: 'Skelly,  Donna',
    OfficeType: 'Constituency',
    Suite: 'Suite 104',
    Street: '2000 Garth Street',
    City: 'Hamilton',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'L9B 0C1',
    EmailAddress: '00',
    Telephone: 'Tel:  905-679-3770',
    Fax: 'Fax:  905-679-0288',
  },
  {
    Honorific: null,
    Name: 'Smith,  Dave',
    OfficeType: 'Constituency',
    Suite: null,
    Street: '236 King Street',
    City: 'Peterborough',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'K9J 7L8',
    EmailAddress: 'dave.smithco@pc.ola.org',
    Telephone: 'Tel:  705-742-3777',
    Fax: 'Fax:  705-742-1822',
  },
  {
    Honorific: 'Hon.',
    Name: 'Smith,  Todd',
    OfficeType: 'Constituency',
    Suite: 'Unit 4',
    Street: '5503 Highway 62 South',
    City: 'Belleville',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'K8N 4Z7',
    EmailAddress: 'todd.smithco@pc.ola.org',
    Telephone: 'Toll Free:  877-536-6248 Tel:  613-962-1144',
    Fax: 'Fax:  613-969-6381',
  },
  {
    Honorific: null,
    Name: 'Stevens,  Jennifer (Jennie)',
    OfficeType: 'Constituency',
    Suite: null,
    Street: '00',
    City: 'St. Catharines',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: '00',
    EmailAddress: 'JStevens-CO@ndp.on.ca',
    Telephone: 'Tel:  905-935-0018',
    Fax: 'Fax:  905-935-0191',
  },
  {
    Honorific: null,
    Name: 'Stiles,  Marit',
    OfficeType: 'Constituency',
    Suite: null,
    Street: '1199 Bloor Street West',
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M6H 1N4',
    EmailAddress: 'MStiles-CO@ndp.on.ca',
    Telephone: 'Tel:  416-535-3158',
    Fax: 'Fax:  416-535-6587',
  },
  {
    Honorific: null,
    Name: 'Surma,  Kinga',
    OfficeType: 'Constituency',
    Suite: 'Unit 102',
    Street: '201 Lloyd Manor Road  Lloydmanor Shopping Centre',
    City: 'Etobicoke',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M9B 6H6',
    EmailAddress: '00',
    Telephone: 'Tel:  416-234-2800',
    Fax: 'Fax:  416-234-2276',
  },
  {
    Honorific: null,
    Name: 'Tabuns,  Peter',
    OfficeType: 'Constituency',
    Suite: null,
    Street: '923 Danforth Avenue',
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M4J 1L8',
    EmailAddress: 'tabunsp-co@ndp.on.ca',
    Telephone: 'Tel:  416-461-0223',
    Fax: 'Fax:  416-461-9542',
  },
  {
    Honorific: null,
    Name: 'Tangri,  Nina',
    OfficeType: 'Constituency',
    Suite: 'Suite 220',
    Street: '2000 Argentia Road  2nd Floor  Plaza IV',
    City: 'Mississauga',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'L5N 1W1',
    EmailAddress: 'nina.tangrico@pc.ola.org',
    Telephone: 'Tel:  905-569-1643',
    Fax: 'Fax:  905-569-6416',
  },
  {
    Honorific: null,
    Name: 'Taylor, Monique',
    OfficeType: 'Constituency',
    Suite: 'Unit 202',
    Street: '555 Concession Street',
    City: 'Hamilton',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'L8V 1A8',
    EmailAddress: 'mtaylor-co@ndp.on.ca',
    Telephone: 'Tel:  905-388-9734',
    Fax: 'Fax:  905-388-7862',
  },
  {
    Honorific: 'Hon.',
    Name: 'Thompson,  Lisa',
    OfficeType: 'Constituency',
    Suite: null,
    Street: '408 Queen Street  P.O. BOX 426',
    City: 'Blyth',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'N0M 1H0',
    EmailAddress: 'lisa.thompsonco@pc.ola.org',
    Telephone: 'Tel:  519-523-4251',
    Fax: 'Fax:  226-523-9296',
  },
  {
    Honorific: 'Hon.',
    Name: 'Thompson,  Lisa',
    OfficeType: 'Constituency',
    Suite: 'Unit 2',
    Street: '807 Queen Street',
    City: 'Kincardine',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'N2Z 2Y2',
    EmailAddress: 'lisa.thompsonco@pc.ola.org',
    Telephone: 'Toll Free:  1-866-396-3007 Tel:  519-396-3007',
    Fax: 'Fax:  519-396-3011',
  },
  {
    Honorific: 'Hon.',
    Name: 'Tibollo,  Michael',
    OfficeType: 'Constituency',
    Suite: 'Unit 3',
    Street: '5100 Rutherford Road',
    City: 'Woodbridge',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'L4H 2J2',
    EmailAddress: 'michael.tibolloco@pc.ola.org',
    Telephone: 'Tel:  905-893-4428',
    Fax: 'Fax:  905-893-4537',
  },
  {
    Honorific: null,
    Name: 'Triantafilopoulos,  Effie',
    OfficeType: 'Constituency',
    Suite: 'Room 124NW',
    Street: 'Main Legislative Building',
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A8',
    EmailAddress: '00',
    Telephone: 'Tel:  905-220-8448',
    Fax: '00',
  },
  {
    Honorific: null,
    Name: 'Vanthof,  John',
    OfficeType: 'Constituency',
    Suite: 'Unit 5',
    Street: '247 Whitewood Avenue  P.O. BOX 398  Pinewoods Centre',
    City: 'New Liskeard',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'P0J 1P0',
    EmailAddress: 'jvanthof-co@ndp.on.ca',
    Telephone: 'Tel:  705-647-5995',
    Fax: 'Fax:  705-647-1976',
  },
  {
    Honorific: null,
    Name: 'Vanthof,  John',
    OfficeType: 'Constituency',
    Suite: null,
    Street: '63B Government Road West',
    City: 'Kirkland Lake',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'P2N 2E6',
    EmailAddress: 'jvanthof-co@ndp.on.ca',
    Telephone: 'Tel:  705-567-4650',
    Fax: 'Fax:  705-567-4208',
  },
  {
    Honorific: null,
    Name: 'Vanthof,  John',
    OfficeType: 'Constituency',
    Suite: null,
    Street: '193 King Street  2nd Floor',
    City: 'Sturgeon Falls',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'P2B 1R8',
    EmailAddress: 'jvanthof-co@ndp.on.ca',
    Telephone: 'Tel:  705-753-0200',
    Fax: 'Fax:  705-753-0800',
  },
  {
    Honorific: null,
    Name: 'Wai, Daisy',
    OfficeType: 'Constituency',
    Suite: 'Suite 311',
    Street: '9555 Yonge Street',
    City: 'Richmond Hill',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'L4C 9M5',
    EmailAddress: 'daisy.waico@pc.ola.org',
    Telephone: 'Tel:  905-884-8080',
    Fax: 'Fax:  905-884-1040',
  },
  {
    Honorific: null,
    Name: 'Walker,  Bill',
    OfficeType: 'Constituency',
    Suite: 'Suite 100',
    Street: '920 1st Avenue West',
    City: 'Owen Sound',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'N4K 4K5',
    EmailAddress: 'bill.walkerco@pc.ola.org',
    Telephone: 'Toll Free:  1-800-461-2664 Tel:  519-371-2421',
    Fax: 'Fax:  519-371-0953',
  },
  {
    Honorific: null,
    Name: 'West,  Jamie',
    OfficeType: 'Constituency',
    Suite: 'Unit 4B',
    Street: '555 Barrydowne Road',
    City: 'Sudbury',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'P3A 3T4',
    EmailAddress: 'JWest-CO@ndp.on.ca',
    Telephone: 'Tel:  705-675-1914',
    Fax: 'Fax:  705-675-1456',
  },
  {
    Honorific: 'Hon.',
    Name: 'Wilson,  Jim',
    OfficeType: 'Constituency',
    Suite: 'Suite 28',
    Street: '180 Parsons Road',
    City: 'Alliston',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'L9R 1E8',
    EmailAddress: 'jim.wilsonco@pc.ola.org',
    Telephone: 'Tel:  705-435-4087',
    Fax: 'Fax:  705-435-1051',
  },
  {
    Honorific: 'Hon.',
    Name: 'Wilson,  Jim',
    OfficeType: 'Constituency',
    Suite: null,
    Street: '50 Hume Street',
    City: 'Collingwood',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'L9Y 1V2',
    EmailAddress: 'jim.wilsonco@pc.ola.org',
    Telephone: 'Toll Free:  1-800-268-7542 Tel:  705-446-1090',
    Fax: 'Fax:  705-446-3397',
  },
  {
    Honorific: null,
    Name: 'Wynne,  Kathleen',
    OfficeType: 'Constituency',
    Suite: 'Suite 101',
    Street: '795 Eglinton Avenue East',
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M4G 4E4',
    EmailAddress: 'kwynne.mpp.co@liberal.ola.org',
    Telephone: 'Tel:  416-425-6777',
    Fax: 'Fax:  416-425-0350',
  },
  {
    Honorific: 'Hon.',
    Name: 'Yakabuski, John',
    OfficeType: 'Constituency',
    Suite: 'Unit 6',
    Street: '84 Isabella Street  The Victoria Center',
    City: 'Pembroke',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'K8A 5S5',
    EmailAddress: 'john.yakabuskico@pc.ola.org',
    Telephone: 'Tel:  613-735-6627',
    Fax: 'Fax:  613-735-6692',
  },
  {
    Honorific: null,
    Name: 'Yarde,  Kevin',
    OfficeType: 'Constituency',
    Suite: 'Unit 7',
    Street: '10215 Kennedy Road North',
    City: 'Brampton',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'L6Z 0C5',
    EmailAddress: 'KYarde-CO@ndp.on.ca',
    Telephone: 'Tel:  905-495-8030',
    Fax: 'Fax:  905-495-1041',
  },
  {
    Honorific: 'Hon.',
    Name: 'Yurek,  Jeff',
    OfficeType: 'Constituency',
    Suite: 'Suite 201',
    Street: '750 Talbot Street',
    City: 'St. Thomas',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'N5P 1E2',
    EmailAddress: 'jeff.yurekco@pc.ola.org',
    Telephone: 'Toll Free:  1-800-265-7638 Tel:  519-631-0666',
    Fax: 'Fax:  519-631-9478',
  },
];

module.exports = mppCont;
