// eachMPP label array captured by scraping. Used to populate findAndUpdate function which creates reference between eachMppdb with both mppConsitituency and bills## db's
const arraylabels = [
  { label: 'Hon. Doug Ford' },
  { label: 'Kathleen O. Wynne' },
  { label: 'Gilles Bisson' },
  { label: 'Jessica Bell' },  
  { label: 'Andrea Horwath' },
  { label: 'Jennifer K. French' },
  { label: 'Rudy Cuzzetto' },
  { label: 'Hon. Victor Fedeli' },
  { label: 'Hon. Raymond Sung Joon Cho' },
  { label: 'Hon. Laurie Scott' },
  { label: 'Randy Pettapiece' },
  { label: 'Doug Downey' },
  { label: 'Lorne Coe' },
  { label: 'Hon. Christine Elliott' },
  { label: 'Lindsey Park' },
  { label: 'Amarjot Sandhu' },
  { label: 'Catherine Fife' },
  { label: 'Kaleed Rasheed' },  
  { label: 'Dave Smith' },
  { label: 'Hon. Rod Phillips' },
  { label: 'Judith Monteith-Farrell' },
  { label: 'Prabmeet Singh Sarkaria' },
  { label: 'Suze Morrison' },
  { label: 'Tom Rakocevic' },
  { label: 'Hon. Monte McNaughton' },
  { label: 'Hon. Greg Rickford' },
  { label: 'Rick Nicholls' },
  { label: 'Sam Oosterhoff' },
  { label: 'Billy Pang' },
  { label: 'Robin Martin' }, 
  { label: 'Peter Tabuns' },
  { label: 'Jeremy Roberts' },
  { label: 'Amy Fee' },
  { label: 'Ian Arthur' },
  { label: 'Michael Parsa' },
  { label: 'Toby Barrett' },
  { label: 'Sol Mamakwa' },
  { label: 'Kevin Yarde' },
  { label: 'Michael Coteau' },
  { label: 'Jill Dunlop' },
  { label: 'Teresa J. Armstrong' },
  { label: 'Logan Kanapathi' },
  { label: 'Nathalie Des Rosiers' },
  { label: 'Sheref Sabawy' },
  { label: 'Bill Walker' },
  { label: 'Michael Gravelle' },
  { label: 'Wayne Gates' },
  { label: 'Taras Natyshak' },
  { label: 'Amanda Simard' },
  { label: 'Guy Bourgouin' },
  { label: 'John Fraser' },
  { label: 'Hon. Merrilee Fullerton' },
  { label: 'Stephen Crawford' },
  { label: 'Percy Hatfield' },
  { label: 'Jane McKenna' },  
  { label: 'Jeff Burch' },
  { label: 'Jill Andrew' },
  { label: 'Hon. Peter Bethlenfalvy' },
  { label: 'Hon. Caroline Mulroney' },
  { label: 'France Gélinas' },
  { label: 'Joel Harden' },
  { label: 'Aris Babikian' },
  { label: 'Christine Hogarth' },
  { label: 'Goldie Ghamari' },
  { label: 'Parm Gill' },
  { label: 'Hon. Ernie Hardeman' },
  { label: 'Mike Harris' },  
  { label: 'Daisy Wai' },
  { label: 'Robert Bailey' },
  { label: 'Doly Begum' },
  { label: 'Sandy Shaw' },
  { label: 'Faisal Hassan' },
  { label: 'Lisa Gretzky' },
  { label: 'Christina Maria Mitas' },
  { label: 'Paul Miller' },
  { label: 'Vincent Ke' },
  { label: 'Hon. Sylvia Jones' },
  { label: 'Hon. Ted Arnott' },
  { label: 'Monique Taylor' },
  { label: 'Andrea Khanjin' },
  { label: 'Deepak Anand' }, 
  { label: 'Bhutila Karpoche' },
  { label: 'Hon. Jeff Yurek' },
  { label: 'Daryl Kramp' },
  { label: 'Hon. Steve Clark' },
  { label: 'Randy Hillier' },
  { label: 'John Vanthof' },
  { label: 'Terence Kernaghan' },
  { label: 'Will Bouma' },
  { label: 'Chris Glover' },
  { label: 'Natalia Kusendova' },
  { label: 'Peggy Sattler' },
  { label: 'Donna Skelly' },
  { label: 'Rima Berns-McGown' },
  { label: 'Hon. Lisa M. Thompson' },
  { label: 'Belinda Karahalios' },
  { label: 'Michael Mantha' },
  { label: 'Mitzie Hunter' },
  { label: 'JenniferStevens' },
  { label: 'Hon. Michael A. Tibollo' },
  { label: 'Paul Calandra' },
  { label: 'Jim McDonell' },
  { label: 'Mike Schreiner' },
  { label: 'Ross Romano' },
  { label: 'Roman Baber' },
  { label: 'Hon. Todd Smith' },
  { label: 'Kinga Surma' },
  { label: 'David Piccini' },
  { label: 'Marie-France Lalonde' },
  { label: 'Effie J. Triantafilopoulos' },
  { label: 'Norman Miller' },
  { label: 'Gila Martow' },
  { label: 'Hon. Lisa MacLeod' },
  { label: 'Jamie West' },
  { label: 'Laura Mae Lindo' },
  { label: 'Sara Singh' },
  { label: 'Stan Cho' },
  { label: 'Vijay Thanigasalam' },
  { label: 'Stephen Lecce' },
  { label: 'Gurratan Singh' },
  { label: 'Hon. John Yakabuski' },
  { label: 'Hon. Jim Wilson' },
  { label: 'Nina Tangri' },
  { label: 'Marit Stiles' },
];

module.exports = arraylabels;
