const seed = [
  {
    Honorific: null,
    Name: 'Anand  Deepak',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 313',
    Street: "Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A8',
    EmailAddress: 'deepak.anand@pc.ola.org',
    Telephone: 'Tel:  416-326-7528',
    Fax: 'Fax:  416-326-7504',
  },
  {
    Honorific: null,
    Name: 'Andrew  Jill',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 115',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A5',
    EmailAddress: 'JAndrew-QP@ndp.on.ca',
    Telephone: 'Tel:  416-325-0071',
    Fax: 'Fax:  416-325-4728',
  },
  {
    Honorific: null,
    Name: 'Armstrong  Teresa',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 159',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A5',
    EmailAddress: 'tarmstrong-qp@ndp.on.ca',
    Telephone: 'Tel:  416-325-1872',
    Fax: 'Fax:  416-325-1912',
  },
  {
    Honorific: 'Hon.',
    Name: 'Arnott  Ted',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 180',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A2',
    EmailAddress: 'ted.arnott@pc.ola.org',
    Telephone: 'Tel:  416-325-3880',
    Fax: 'Fax:  416-325-6649',
  },
  {
    Honorific: null,
    Name: 'Arthur  Ian',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 203',
    Street: "North Wing  Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A8',
    EmailAddress: 'IArthur-QP@ndp.on.ca',
    Telephone: 'Tel:  416-325-0168 Tel:  519-787-5247',
    Fax: 'Fax:  416-325-0088',
  },
  {
    Honorific: null,
    Name: 'Baber  Roman',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 472',
    Street: "Main Legislative Building Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A8',
    EmailAddress: 'roman.baber@pc.ola.org',
    Telephone: 'Tel:  416-326-7114',
    Fax: 'Fax:  416-326-7113',
  },
  {
    Honorific: null,
    Name: 'Babikian  Aris',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room N404',
    Street: "Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A8',
    EmailAddress: 'aris.babikian@pc.ola.org',
    Telephone: 'Tel:  416-326-7111',
    Fax: 'Fax:  416-326-7099',
  },
  {
    Honorific: null,
    Name: 'Doly  Begum',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 385',
    Street: "Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A5',
    EmailAddress: 'DBegum-QP@ndp.on.ca',
    Telephone: 'Tel:  416-325-0908',
    Fax: 'Fax:  416-325-0685',
  },
  {
    Honorific: null,
    Name: 'Jessica  Bell  (University—Rosedale)',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 372',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A5',
    EmailAddress: 'JBell-QP@ndp.on.ca',
    Telephone: 'Tel:  416-325-1620',
    Fax: 'Fax:  416-325-1424',
  },
  {
    Honorific: null,
    Name: 'Berns-McGown  Rima',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 241',
    Street: "North Wing  Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A8',
    EmailAddress: 'RBerns-McGown-QP@ndp.on.ca',
    Telephone: 'Tel:  416-325-2881',
    Fax: 'Fax:  416-325-2780',
  },
  {
    Honorific: null,
    Name: 'Bisson  Gilles',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 114',
    Street: "Main Legislative Building Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A5',
    EmailAddress: 'gbisson@ndp.on.ca',
    Telephone: 'Tel:  416-325-7122',
    Fax: 'Fax:  416-325-7181',
  },
  {
    Honorific: null,
    Name: 'Bouma  Will',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 269',
    Street: "Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A8',
    EmailAddress: 'will.bouma@pc.ola.org',
    Telephone: 'Tel:  416-326-7092',
    Fax: 'Fax:  416-326-7199',
  },
  {
    Honorific: null,
    Name: 'Bourgouin  Guy',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 116',
    Street: "Main Legislative Building Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A5',
    EmailAddress: 'GBourgouin-QP@ndp.on.ca',
    Telephone: 'Tel:  416-326-7351',
    Fax: 'Fax:  416-326-6972',
  },
  {
    Honorific: null,
    Name: 'Burch  Jeff',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 355',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A8',
    EmailAddress: 'JBurch-QP@ndp.on.ca',
    Telephone: 'Tel:  416-325-3990',
    Fax: 'Fax:  416-325-3415',
  },
  {
    Honorific: null,
    Name: 'Coe  Lorne',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 211',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A8',
    EmailAddress: 'lorne.coe@pc.ola.org',
    Telephone: 'Tel:  416-325-1331',
    Fax: 'Fax:  416-325-1423',
  },
  {
    Honorific: null,
    Name: 'Coteau  Michael',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 416',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A8',
    EmailAddress: '00',
    Telephone: 'Tel:  416-325-4544',
    Fax: 'Fax:  416-325-4525',
  },
  {
    Honorific: null,
    Name: 'Stephen  Crawford  (Oakville)',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 271',
    Street: "Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A8',
    EmailAddress: 'stephen.crawford@pc.ola.org',
    Telephone: 'Tel:  416-326-7323',
    Fax: 'Fax:  416-326-7319',
  },
  {
    Honorific: null,
    Name: 'Rudy Cuzzetto',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 261',
    Street: "Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A8',
    EmailAddress: 'rudy.cuzzetto@pc.ola.org',
    Telephone: 'Tel:  416-326-7239',
    Fax: 'Fax:  416-326-7233',
  },
  {
    Honorific: null,
    Name: 'Des Rosiers  Nathalie',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 411',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A8',
    EmailAddress: '00',
    Telephone: 'Tel:  416-325-4163',
    Fax: 'Fax:  416-325-4147',
  },
  {
    Honorific: null,
    Name: 'Dunlop  Jill',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 445',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A8',
    EmailAddress: 'jill.dunlop@pc.ola.org',
    Telephone: 'Tel:  416-326-7281',
    Fax: 'Fax:  416-326-6887',
  },
  {
    Honorific: null,
    Name: 'Fife  Catherine',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 154',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A5',
    EmailAddress: 'cfife-qp@ndp.on.ca',
    Telephone: 'Tel:  416-325-6913',
    Fax: 'Fax:  416-325-6942',
  },
  {
    Honorific: null,
    Name: 'Fraser  John',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 448',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A2',
    EmailAddress: '000',
    Telephone: 'Tel:  416-325-4670',
    Fax: 'Fax:  416-325-4671',
  },
  {
    Honorific: null,
    Name: 'Jennifer K. French',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 185',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A5',
    EmailAddress: 'JFrench-QP@ndp.on.ca',
    Telephone: 'Tel:  416-325-0117',
    Fax: 'Fax:  416-325-0084',
  },
  {
    Honorific: null,
    Name: 'Wayne Gates',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 169',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A5',
    EmailAddress: 'wgates-qp@ndp.on.ca',
    Telephone: 'Tel:  416-212-6102',
    Fax: 'Fax:  416-212-6106',
  },
  {
    Honorific: null,
    Name: 'France  Gélinas  (Nickel Belt)',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 186',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A5',
    EmailAddress: 'fgelinas-qp@ndp.on.ca',
    Telephone: 'Tel:  416-325-9203',
    Fax: 'Fax:  416-325-9185',
  },
  {
    Honorific: null,
    Name: 'Ghamari  Goldie',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 316',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A8',
    EmailAddress: 'goldie.ghamari@pc.ola.org',
    Telephone: 'Tel:  416-325-4890',
    Fax: 'Fax:  416-325-4885',
  },
  {
    Honorific: null,
    Name: 'Gill  Parm',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 263',
    Street: 'Legislative Building  Queen&#039;s Park',
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A8',
    EmailAddress: 'parm.gill@pc.ola.org',
    Telephone: 'Tel:  416-326-7022',
    Fax: 'Fax:  416-326-7049',
  },
  {
    Honorific: null,
    Name: 'Glover  Chris',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 343',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A8',
    EmailAddress: 'CGlover-QP@ndp.on.ca',
    Telephone: 'Tel:  416-326-7196',
    Fax: 'Fax:  416-326-7172',
  },
  {
    Honorific: null,
    Name: 'Gravelle  Michael',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 421',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A8',
    EmailAddress: '000',
    Telephone: 'Tel:  416-325-4757',
    Fax: 'Fax:  416-325-4752',
  },
  {
    Honorific: null,
    Name: 'Lisa  Gretzky  (Windsor West)',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 172',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A5',
    EmailAddress: 'LGretzky-QP@ndp.on.ca',
    Telephone: 'Tel:  416-325-0235',
    Fax: 'Fax:  416-325-0873',
  },
  {
    Honorific: null,
    Name: 'Harden  Joel',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 328',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A8',
    EmailAddress: 'JHarden-QP@ndp.on.ca',
    Telephone: 'Tel:  416-326-7648',
    Fax: 'Fax:  416-326-7639',
  },
  {
    Honorific: null,
    Name: 'Harris  Mike',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 434',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A8',
    EmailAddress: 'mike.harris@pc.ola.org',
    Telephone: 'Tel:  416-326-6945',
    Fax: 'Fax:  416-326-6942',
  },
  {
    Honorific: null,
    Name: 'Hassan  Faisal',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 112',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A5',
    EmailAddress: 'FHassan-QP@ndp.on.ca',
    Telephone: 'Tel:  416-326-6961',
    Fax: 'Fax:  416-326-6957',
  },
  {
    Honorific: null,
    Name: 'Hatfield  Percy',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 363',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A5',
    EmailAddress: 'PHatfield-QP@ndp.on.ca',
    Telephone: 'Tel:  416-325-6773',
    Fax: 'Fax:  416-325-6795',
  },
  {
    Honorific: null,
    Name: 'Hillier  Randy',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 436',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A8',
    EmailAddress: 'randy.hillier@pc.ola.org',
    Telephone: 'Tel:  416-325-2244',
    Fax: 'Fax:  416-325-2106',
  },
  {
    Honorific: null,
    Name: 'Horwath  Andrea',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 381',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A8',
    EmailAddress: 'ahorwath-qp@ndp.on.ca',
    Telephone: 'Tel:  416-325-7116',
    Fax: 'Fax:  416-325-8222',
  },
  {
    Honorific: null,
    Name: 'Hunter  Mitzie',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 447',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A8',
    EmailAddress: '000',
    Telephone: 'Tel:  416-325-4800',
    Fax: 'Fax:  416-325-4785',
  },
  {
    Honorific: null,
    Name: 'Kanapathi  Logan',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 443',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A8',
    EmailAddress: 'logan.kanapathi@pc.ola.org',
    Telephone: 'Tel:  416-325-4850',
    Fax: 'Fax:  416-325-4884',
  },
  {
    Honorific: null,
    Name: 'Karpoche  Bhutila',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 204',
    Street: "North Wing  Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A8',
    EmailAddress: 'BKarpoche-QP@ndp.on.ca',
    Telephone: 'Tel:  416-325-3017',
    Fax: 'Fax:  416-325-2937',
  },
  {
    Honorific: null,
    Name: 'Kernaghan  Terence',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 362',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A8',
    EmailAddress: 'TKernaghan-QP@ndp.on.ca',
    Telephone: 'Tel:  416-326-7568',
    Fax: 'Fax:  416-326-7580',
  },
  {
    Honorific: null,
    Name: 'Kramp  Daryl',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 325',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A2',
    EmailAddress: 'daryl.kramp@pc.ola.org',
    Telephone: 'Tel:  416-326-7005',
    Fax: 'Fax:  416-326-6999',
  },
  {
    Honorific: null,
    Name: 'Kusendova  Natalia',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 429',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A8',
    EmailAddress: 'natalia.kusendova@pc.ola.org',
    Telephone: 'Tel:  416-326-7102',
    Fax: 'ax:  416-326-7100',
  },
  {
    Honorific: null,
    Name: 'Marie-France  Lalonde  (Orléans)',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 413',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A8',
    EmailAddress: '000',
    Telephone: 'Tel:  416-325-4405',
    Fax: 'Fax:  416-325-4395',
  },
  {
    Honorific: null,
    Name: 'Laura Mae  Lindo  (Kitchener Centre)',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 170',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A5',
    EmailAddress: 'LLindo-QP@ndp.on.ca',
    Telephone: 'Tel:  416-326-7221',
    Fax: 'Fax:  416-326-7217',
  },
  {
    Honorific: null,
    Name: 'Mamakwa  Sol',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room N201',
    Street: 'Street  Legislative Building  Queen&#039;s Park',
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A5',
    EmailAddress: 'SMamakwa-QP@ndp.on.ca',
    Telephone: '0000',
    Fax: null,
  },
  {
    Honorific: null,
    Name: 'Mantha  Michael',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 160',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A5',
    EmailAddress: 'mmantha-qp@ndp.on.ca',
    Telephone: 'Tel:  416-325-1938',
    Fax: 'Fax:  416-325-1976',
  },
  {
    Honorific: null,
    Name: 'Jane  McKenna  (Burlington)',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 321',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A8',
    EmailAddress: 'jane.mckenna@pc.ola.org',
    Telephone: 'Tel:  416-325-4910',
    Fax: 'Fax:  416-325-4905',
  },
  {
    Honorific: null,
    Name: 'Norman  Miller  (Parry Sound—Muskoka)',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 357',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A5',
    EmailAddress: 'pmiller-qp@ndp.on.ca',
    Telephone: 'Tel:  416-325-0707',
    Fax: 'Fax:  416-325-0853',
  },
  {
    Honorific: null,
    Name: 'Miller  Norman',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 440',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A8',
    EmailAddress: 'norm.miller@pc.ola.org',
    Telephone: 'Tel:  416-325-1012',
    Fax: 'Fax:  416-325-1153',
  },
  {
    Honorific: null,
    Name: 'Christina Maria Mitas  (Scarborough Centre)',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 427',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A8',
    EmailAddress: 'christina.mitas@pc.ola.org',
    Telephone: 'Tel:  416-326-7374',
    Fax: 'Fax:  416-326-7377',
  },
  {
    Honorific: null,
    Name: 'Judith  Monteith-Farrell  (Thunder Bay—Atikokan)',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 207',
    Street: "North Wing  Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A8',
    EmailAddress: 'JMonteith-Farrell-QP@ndp.on.ca',
    Telephone: 'Tel:  416-325-9820',
    Fax: 'Fax:  416-325-9800',
  },
  {
    Honorific: null,
    Name: 'Suze  Morrison  (Toronto Centre)',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 345',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A5',
    EmailAddress: 'SMorrison-QP@ndp.on.ca',
    Telephone: 'Tel:  416-326-7171',
    Fax: 'Fax:  416-326-7188',
  },
  {
    Honorific: null,
    Name: 'Taras  Natyshak  (Essex)',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 369',
    Street: "Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A5',
    EmailAddress: 'tnatyshak-qp@ndp.on.ca',
    Telephone: 'Tel:  416-325-0714',
    Fax: 'Fax:  416-325-0980',
  },
  {
    Honorific: null,
    Name: 'Nicholls  Rick',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 440',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A8',
    EmailAddress: 'rick.nicholls@pc.ola.org',
    Telephone: 'Tel:  416-325-9099',
    Fax: 'ax:  416-325-9000',
  },
  {
    Honorific: null,
    Name: 'Billy  Pang  (Markham—Unionville)',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 260',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A8',
    EmailAddress: 'billy.pang@pc.ola.org',
    Telephone: 'Tel:  416-325-4960',
    Fax: 'Fax:  416-325-0101',
  },
  {
    Honorific: null,
    Name: 'Rakocevic  Tom',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 330',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A8',
    EmailAddress: 'TRakocevic-QP@ndp.on.ca',
    Telephone: 'Tel:  416-326-7585',
    Fax: 'Fax:  416-326-7634',
  },
  {
    Honorific: null,
    Name: 'Rasheed  Kaleed',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room N406',
    Street: "Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A8',
    EmailAddress: 'kaleed.rasheed@pc.ola.org',
    Telephone: 'Tel:  416-326-7028',
    Fax: 'Fax:  416-326-7085',
  },
  {
    Honorific: null,
    Name: 'Roberts  Jeremy',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 461',
    Street: "Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A8',
    EmailAddress: 'jeremy.roberts@pc.ola.org',
    Telephone: 'Tel:  416-326-7458',
    Fax: 'Fax:  416-326-7470',
  },
  {
    Honorific: null,
    Name: 'Sabawy  Sheref',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room N407',
    Street: "Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A8',
    EmailAddress: 'sheref.sabawy@pc.ola.org',
    Telephone: 'Tel:  416-326-7253',
    Fax: 'Fax:  416-326-7244',
  },
  {
    Honorific: null,
    Name: 'Sandhu  Amarjot',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 471',
    Street: "Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A8',
    EmailAddress: 'amarjot.sandhu@pc.ola.org',
    Telephone: 'Tel:  416-326-6903',
    Fax: 'Fax:  416-326-6899',
  },
  {
    Honorific: null,
    Name: 'Peggy  Sattler  (London West)',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 359',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A8',
    EmailAddress: 'Psattler-qp@ndp.on.ca',
    Telephone: 'Tel:  416-325-6908',
    Fax: 'Fax:  416-325-7030',
  },
  {
    Honorific: null,
    Name: 'Schreiner  Mike',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 451',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A2',
    EmailAddress: 'Mschreiner@ola.org',
    Telephone: 'Tel:  416-325-4664',
    Fax: 'Fax:  416-325-4666',
  },
  {
    Honorific: null,
    Name: 'Shaw  Sandy',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 202',
    Street: "North Wing  Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A8',
    EmaiAddress: 'SShaw-QP@ndp.on.ca',
    Telephone: 'Tel:  416-326-6890',
    Fax: 'Fax:  416-326-6885',
  },
  {
    Honorific: null,
    Name: 'Singh  Gurratan',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 156',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A5',
    EmailAddress: 'GSingh-QP@ndp.on.ca',
    Telephone: 'Tel:  416-326-7178',
    Fax: 'Fax:  416-326-7166',
  },
  {
    Honorific: null,
    Name: 'Singh  Sara',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 331',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A8',
    EmailAddress: 'SSingh-QP@ndp.on.ca',
    Telephone: 'Tel:  416-326-7610',
    Fax: 'Fax:  416-326-7615',
  },
  {
    Honorific: null,
    Name: 'Smith  Dave',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 320',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A4',
    EmailAddress: 'dave.smith@pc.ola.org',
    Telephone: 'Tel:  416-326-7406',
    Fax: 'Fax:  416-326-7390',
  },
  {
    Honorific: 'Hon.',
    Name: 'Smith  Todd',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 223',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A2',
    EmailAddress: null,
    Telephone: 'Tel:  416-325-7754',
    Fax: 'Fax:  416-325-7755',
  },
  {
    Honorific: null,
    Name: 'Stevens  Jennifer (Jennie)',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 387',
    Street: "Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A5',
    EmailAddress: 'JStevens-QP@ndp.on.ca',
    Telephone: 'Tel:  416-326-7127',
    Fax: 'Fax:  416-326-7126',
  },
  {
    Honorific: null,
    Name: 'Stiles  Marit',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 157',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A5',
    EmailAddress: 'MStiles-QP@ndp.on.ca',
    Telephone: 'Tel:  416-326-7202',
    Fax: 'Fax:  416-326-7200',
  },
  {
    Honorific: null,
    Name: 'Tabuns  Peter',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 165',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A5',
    EmailAddress: 'tabunsp-qp@ndp.on.ca',
    Telephone: 'Tel:  416-325-3250',
    Fax: 'Fax:  416-325-3252',
  },
  {
    Honorific: null,
    Name: 'Tangri  Nina',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 425',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A8',
    EmailAddress: 'nina.tangri@pc.ola.org',
    Telephone: 'Tel:  416-326-7286',
    Fax: 'Fax:  416-326-7347',
  },
  {
    Honorific: null,
    Name: 'Monique  Taylor  (Hamilton Mountain)',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 371',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A4',
    EmailAddress: 'mtaylor-qp@ndp.on.ca',
    Telephone: 'Tel:  416-325-1796',
    Fax: 'Fax:  416-325-1863',
  },
  {
    Honorific: null,
    Name: 'Thanigasalam  Vijay',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 212',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A4',
    EmailAddress: 'vijay.thanigasalam@pc.ola.org',
    Telephone: 'Tel:  416-326-7274',
    Fax: 'Fax:  416-326-7272',
  },
  {
    Honorific: null,
    Name: 'Vanthof  John',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 348',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A8',
    EmailAddress: 'jvanthof-qp@ndp.on.ca',
    Telephone: 'Tel:  416-325-2000',
    Fax: 'Fax:  416-325-1999',
  },
  {
    Honorific: null,
    Name: 'Wai  Daisy',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 265',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A8',
    EmailAddress: 'daisy.wai@pc.ola.org',
    Telephone: 'Tel:  416-325-4265',
    Fax: 'Fax:  416-325-4289',
  },
  {
    Honorific: null,
    Name: 'Walker  Bill',
    OfficeType: "Queen's Park",
    Department: 'Government Caucus Office',
    Suite: 'Room 251',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A4',
    EmailAddress: 'bill.walker@pc.ola.org',
    Telephone: 'Tel:  416-325-6242',
    Fax: 'Fax:  416-325-6248',
  },
  {
    Honorific: null,
    Name: 'Jamie West',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 347',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A8',
    EmailAddress: 'JWest-QP@ndp.on.ca',
    Telephone: 'Tel:  416-326-7144',
    Fax: 'Fax:  416-326-7280',
  },
  {
    Honorific: null,
    Name: 'Kathleen Wynne',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 420',
    Street: "Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A8',
    EmailAddress: null,
    Telephone: 'Tel:  416-325-4705',
    Fax: 'Fax:  416-325-4726',
  },
  {
    Honorific: null,
    Name: 'Kevin Yarde',
    OfficeType: "Queen's Park",
    Department: null,
    Suite: 'Room 206',
    Street: "North Wing  Main Legislative Building  Queen's Park",
    City: 'Toronto',
    Province: 'Ontario',
    Country: 'Canada',
    PostalCode: 'M7A 1A8',
    EmailAddress: 'KYarde-QP@ndp.on.ca',
    Telephone: 'Tel:  416-326-6727',
    Fax: 'Fax:  416-326-6726',
  },
];
export default seed;
